'use strict';
const DB_NAME='gt_db_v2'; const DB_VERSION=1;
let db, state={route:'track', persons:[], drinks:[], packages:[], logs:[], selectedPerson:null, query:'', cat:'Alle'};
const $=s=>document.querySelector(s); const eur=n=>(Number(n)||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;['settings','persons','drinks','logs'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
async function load(){state.persons=await all('persons'); state.drinks=await all('drinks'); state.logs=(await all('logs')).sort((a,b)=>b.ts-a.ts); if(!state.selectedPerson&&state.persons[0])state.selectedPerson=state.persons[0].id;}
async function bootstrap(){db=await openDb(); const has=(await all('drinks')).length; state.packages=await fetch('data/pakete.json').then(r=>r.json()).catch(()=>[]); if(!has){const data=await fetch('data/barkarte.json').then(r=>r.json()); for(const d of data.drinks) await put('drinks',d);} await load(); bindNav(); render(); if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js');}
function bindNav(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;render();}); $('#menuBtn').onclick=()=>$('#menuDialog').showModal(); $('#menuDialog').addEventListener('close',e=>{const v=$('#menuDialog').returnValue;if(['settings','data'].includes(v)){state.route=v;render();}});}
function setRoute(r){state.route=r;render();}
function render(){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route)); const v=$('#view'); if(state.route==='track')v.innerHTML=viewTrack(); if(state.route==='stats')v.innerHTML=viewStats(); if(state.route==='data')v.innerHTML=viewData(); if(state.route==='settings')v.innerHTML=viewSettings(); bindView();}
function pkgName(id){return (state.packages.find(p=>p.id===id)||{}).name||id||'Kein Paket'}
function pkgStatus(d,pid){if(!pid||pid==='none')return 'not_included'; return (d.packages&&d.packages[pid])||'unclear'}
function statusBadge(s){return s==='included'?'<span class="badge ok">enthalten</span>':s==='not_included'?'<span class="badge bad">nicht enthalten</span>':'<span class="badge warn">unklar</span>'}
function viewTrack(){if(!state.persons.length)return `<section class="grid"><div class="card"><h2>Ersteinrichtung erforderlich</h2><p>Lege zuerst Personen und Pakete an.</p><button class="primary" data-action="setup">Setup starten</button></div></section>`; const cats=['Alle',...new Set(state.drinks.map(d=>d.category).filter(Boolean))]; const person=state.persons.find(p=>p.id===state.selectedPerson)||state.persons[0]; const drinks=state.drinks.filter(d=>(state.cat==='Alle'||d.category===state.cat)&&(!state.query||(`${d.name} ${d.category}`).toLowerCase().includes(state.query.toLowerCase()))); return `<section class="grid"><div class="chips">${state.persons.map(p=>`<button class="chip ${p.id===person.id?'active':''}" data-person="${p.id}">${p.name}</button>`).join('')}</div><div class="card stack"><input id="search" placeholder="Getränk suchen" value="${state.query}"><div class="chips">${cats.map(c=>`<button class="chip ${c===state.cat?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div></div><div class="grid">${drinks.map(d=>{const s=pkgStatus(d,person.packageId);return `<button class="card drink" data-log="${d.id}"><span><span class="drink-title">${d.name}</span><br><span class="muted">${d.category||''} · ${statusBadge(s)}</span></span><span class="price">${eur(d.price)}</span></button>`}).join('')||'<div class="notice">Keine Treffer.</div>'}</div></section>`;}
function viewStats(){const rows=state.persons.map(p=>{const logs=state.logs.filter(l=>l.personId===p.id); const total=logs.reduce((s,l)=>s+(Number(l.price)||0),0); const included=logs.filter(l=>l.status==='included').reduce((s,l)=>s+(Number(l.price)||0),0); const cost=Number(p.packagePrice)||0; const saving=included-cost; return {p,logs,total,included,cost,saving};}); return `<section class="grid"><div class="card"><h2>Auswertung</h2>${rows.map(r=>`<div class="stat"><span><b>${r.p.name}</b><br><span class="muted">${pkgName(r.p.packageId)} · ${r.logs.length} Getränke</span></span><span>${eur(r.total)}</span></div><div class="stat"><span>Davon im Paket bewertet</span><span>${eur(r.included)}</span></div><div class="stat"><span>Paketpreis</span><span>${eur(r.cost)}</span></div><div class="stat"><span>Konservative Ersparnis</span><span>${eur(r.saving)}</span></div>`).join('')||'<p>Keine Personen angelegt.</p>'}</div><div class="card"><h3>Letzte Einträge</h3>${state.logs.slice(0,10).map(l=>`<div class="stat"><span>${new Date(l.ts).toLocaleString('de-DE')}<br><span class="muted">${l.personName} · ${l.drinkName}</span></span><span>${eur(l.price)}</span></div>`).join('')||'<p>Keine Einträge.</p>'}</div></section>`;}
function viewSettings(){return `<section class="grid"><div class="card stack"><h2>Person anlegen</h2><div class="field"><label>Name</label><input id="pName" placeholder="z. B. Fabian"></div><div class="field"><label>Getränkepaket</label><select id="pPkg">${state.packages.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div class="field"><label>Paketpreis gesamt</label><input id="pPrice" type="number" step="0.01" placeholder="0,00"></div><button class="primary" data-action="addPerson">Person speichern</button></div><div class="card"><h2>Personen</h2>${state.persons.map(p=>`<div class="stat"><span><b>${p.name}</b><br><span class="muted">${pkgName(p.packageId)} · ${eur(p.packagePrice)}</span></span><button class="secondary" data-delete-person="${p.id}">Löschen</button></div>`).join('')||'<p>Noch keine Personen.</p>'}</div></section>`;}
function viewData(){return `<section class="grid"><div class="card stack"><h2>Import / Export</h2><button class="primary" data-action="export">Backup exportieren</button><button class="secondary" data-action="importBackup">Backup importieren</button><button class="secondary" data-action="importBarkarte">Barkarte importieren (JSON/CSV/Text)</button><div class="notice">PDF-Auslesen ist lokal im Browser nur eingeschränkt zuverlässig. Für belastbare Paketlogik sollte die Barkarte als strukturierte JSON/CSV-Datei importiert werden.</div></div><div class="card"><h3>Datenbestand</h3><p>${state.drinks.length} Getränke · ${state.logs.length} Einträge · ${state.persons.length} Personen</p></div></section>`;}
function bindView(){document.querySelectorAll('[data-route]').forEach(()=>{}); document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{state.selectedPerson=b.dataset.person;render();}); document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render();}); const s=$('#search'); if(s)s.oninput=e=>{state.query=e.target.value;render();}; document.querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>addLog(b.dataset.log)); document.querySelectorAll('[data-delete-person]').forEach(b=>b.onclick=()=>deletePerson(b.dataset.deletePerson)); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]&&actions[b.dataset.action]());}
async function addLog(drinkId){const p=state.persons.find(x=>x.id===state.selectedPerson), d=state.drinks.find(x=>x.id===drinkId); if(!p||!d)return; await put('logs',{id:uid(),ts:Date.now(),personId:p.id,personName:p.name,drinkId:d.id,drinkName:d.name,price:Number(d.price)||0,status:pkgStatus(d,p.packageId)}); await load(); render();}
async function deletePerson(id){if(confirm('Person und zugehörige Einträge löschen?')){await del('persons',id); for(const l of state.logs.filter(x=>x.personId===id)) await del('logs',l.id); await load(); render();}}
const actions={setup(){setRoute('settings')},async addPerson(){const name=$('#pName').value.trim(); if(!name)return alert('Name fehlt.'); await put('persons',{id:uid(),name,packageId:$('#pPkg').value,packagePrice:Number($('#pPrice').value)||0}); await load(); state.route='track'; render();},export(){const data={version:'2.0.0',exportedAt:new Date().toISOString(),persons:state.persons,drinks:state.drinks,logs:state.logs}; download(JSON.stringify(data,null,2),'getraenketracker-backup.json','application/json');},importBackup(){pick('.json',async text=>{const data=JSON.parse(text); for(const p of data.persons||[])await put('persons',p); for(const d of data.drinks||[])await put('drinks',d); for(const l of data.logs||[])await put('logs',l); await load(); render();});},importBarkarte(){pick('.json,.csv,.txt',async text=>{let drinks=[]; if(text.trim().startsWith('{')||text.trim().startsWith('[')){const data=JSON.parse(text); drinks=Array.isArray(data)?data:(data.drinks||[]);} else {drinks=parseCsvDrinks(text);} if(!drinks.length)return alert('Keine Getränke erkannt.'); let changed=0; for(const d of drinks){d.id=d.id||slug(d.name); d.packages=d.packages||{}; await put('drinks',d); changed++;} await load(); alert(`${changed} Getränke importiert/aktualisiert.`); render();});}};
function pick(accept,cb){const i=$('#fileInput'); i.accept=accept; i.onchange=()=>{const f=i.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>cb(String(r.result)); r.readAsText(f); i.value='';}; i.click();}
function parseCsvDrinks(text){const lines=text.split(/\r?\n/).filter(Boolean); const head=lines.shift().split(';').map(x=>x.trim().toLowerCase()); return lines.map(line=>{const c=line.split(';'); const obj={}; head.forEach((h,i)=>obj[h]=c[i]); return {id:slug(obj.id||obj.name),name:obj.name||obj.getränk||obj.getraenk,category:obj.category||obj.kategorie||'Import',price:Number(String(obj.price||obj.preis||'0').replace(',','.')),packages:{}};}).filter(d=>d.name);}
function slug(s){return String(s||'getraenk').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')+'_'+uid().slice(0,4)}
function download(content,name,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),500);}
bootstrap().catch(e=>{console.error(e); $('#view').innerHTML='<div class="card"><h2>Fehler beim Start</h2><p>'+e.message+'</p></div>';});
