'use strict';
const DB_NAME='gt_db_v3';
const DB_VERSION=5;
const APP_VERSION='3.0.0';
const DATA_VERSION='2025-11-01_aida_barkarte_v3_0';
const CHANGELOG=[
 {v:'3.0.0',items:['Hauptversion mit Dashboard und iPhone-Bottom-Navigation','Mehrfach nutzbare Reiseverwaltung als Kernfunktion','Export/Import zum Zusammenführen mehrerer Geräte','Geräte-ID und Gerätename in jedem Verlaufseintrag','Favoriten, zuletzt getrunken und gängige Getränke priorisiert','Bearbeiten und Löschen falsch erfasster Einträge','Changelog und Versionsinfo direkt in der App']},
 {v:'2.4.0',items:['Reiseverwaltung für mehrfachen Einsatz ergänzt','Auswertung konsequent pro ausgewählter Reise','Eindeutige Geräte-ID je Installation','Import/Export mit Merge-Logik gegen doppelte Einträge','Verlauf zeigt: konsumierende Person und erfassendes Gerät']},
 {v:'2.3.0',items:['Favoriten eingeführt','Verlauf bearbeiten und löschen','Navigation oben ergänzt','Getränke nicht mehr rein alphabetisch sortiert']},
 {v:'2.2.0',items:['AIDA Barkarte Stand 01.11.2025 als strukturierte Stammdaten','Paketnamen ALL IN, FUN, Kids & Teens ALL IN, Kids & Teens FUN']},
 {v:'2.1.0',items:['iPhone-Layout kompakter']}
];
let db;
let state={route:'home',settings:{},trips:[],persons:[],drinks:[],packages:[],logs:[],favorites:[],selectedPerson:null,selectedTrip:null,query:'',cat:'Empfohlen'};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const eur=n=>(Number(n)||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const preferredCategories=['Empfohlen','Favoriten','Heißgetränke','Softdrinks','Wasser','Säfte, Nektare & Schorlen','Juicy Cocktails','Kids & Teens Cocktails','Milchshakes','Biere','Longdrinks','Sprizz','Cocktails','Weine','Prickelndes','Spirituosen','Alle'];
const quickTerms=['kaffee','cappuccino','latte','espresso','kakao','tee','coca-cola','cola','fanta','sprite','wasser','mineralwasser','sodawasser','apfelsaft','orangensaft','aida iced tea','aida lemonade','dodo','erdbeer-milchshake','radeberger pilsner','aperol sprizz','hugo'];
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;['settings','persons','drinks','logs','trips'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function get(store,id){return new Promise((res,rej)=>{const r=tx(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function uid(){return Math.random().toString(36).slice(2,10)+Date.now().toString(36)}
function deviceUid(){return 'dev_'+uid()+'_'+Math.random().toString(36).slice(2,6)}
async function getSetting(id){return get('settings',id)}
async function putSetting(id,value){await put('settings',{id,value,updatedAt:new Date().toISOString()});state.settings[id]=value;}
async function ensureDefaults(){
 const did=await getSetting('deviceId'); if(!did) await putSetting('deviceId',deviceUid()); else state.settings.deviceId=did.value;
 const dn=await getSetting('deviceName'); if(!dn) await putSetting('deviceName','Dieses Gerät'); else state.settings.deviceName=dn.value;
 const fav=await getSetting('favorites'); state.favorites=(fav&&fav.value)||[];
 state.trips=await all('trips');
 if(!state.trips.length){const t={id:'trip_'+uid(),name:'Aktuelle Reise',ship:'',startDate:'',endDate:'',tripKey:'aktuelle_reise',createdAt:new Date().toISOString()};await put('trips',t);await putSetting('currentTripId',t.id);state.trips=[t];}
 const cur=await getSetting('currentTripId'); state.selectedTrip=(cur&&cur.value)||state.trips[0].id;
}
async function migrateLegacy(){
 const persons=await all('persons'); const logs=await all('logs'); const curTrip=state.selectedTrip||state.trips[0]?.id;
 for(const p of persons){if(!p.tripId){p.tripId=curTrip; await put('persons',p);}}
 for(const l of logs){let changed=false;if(!l.tripId){l.tripId=curTrip;changed=true;} if(!l.trackedByDeviceId){l.trackedByDeviceId=state.settings.deviceId;changed=true;} if(!l.trackedByDeviceName){l.trackedByDeviceName=state.settings.deviceName;changed=true;} if(changed)await put('logs',l);}
}
async function load(){state.trips=(await all('trips')).sort((a,b)=>(b.startDate||'').localeCompare(a.startDate||''));state.persons=await all('persons');state.drinks=await all('drinks');state.logs=(await all('logs')).sort((a,b)=>b.ts-a.ts);const fav=await getSetting('favorites');state.favorites=(fav&&fav.value)||[];if(!state.trips.find(t=>t.id===state.selectedTrip))state.selectedTrip=state.trips[0]?.id||null;if(!state.selectedPerson||!currentPersons().find(p=>p.id===state.selectedPerson))state.selectedPerson=currentPersons()[0]?.id||null;}
async function bootstrap(){db=await openDb();state.packages=await fetch('data/pakete.json').then(r=>r.json()).catch(()=>[]);await ensureDefaults();const data=await fetch('data/barkarte.json').then(r=>r.json());const current=await getSetting('barkarteVersion');const has=(await all('drinks')).length;if(!has||!current||current.value!==DATA_VERSION){for(const d of data.drinks) await put('drinks',d);await putSetting('barkarteVersion',{version:DATA_VERSION,source:data.source||'AIDA Barkarte',updatedAt:new Date().toISOString(),count:data.drinks.length});}
 await migrateLegacy(); await putSetting('appVersion',APP_VERSION); await load(); bindStatic(); render(); if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js');}
function bindStatic(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-route]');if(nav){state.route=nav.dataset.route;render();}});$('#menuBtn').onclick=()=>$('#menuDialog').showModal();$('#menuDialog').addEventListener('close',()=>{const v=$('#menuDialog').returnValue;if(v&&v!=='close'){state.route=v;render();}});$('#editDialog').addEventListener('close',()=>{if($('#editDialog').returnValue==='save')saveEditLog();});}
function currentTrip(){return state.trips.find(t=>t.id===state.selectedTrip)||state.trips[0]||null}
function currentPersons(){return state.persons.filter(p=>p.tripId===state.selectedTrip)}
function currentLogs(){return state.logs.filter(l=>l.tripId===state.selectedTrip)}
function setSubtitle(){const t=currentTrip();const p=currentPersons().find(x=>x.id===state.selectedPerson);$('#subtitle').textContent=`v${APP_VERSION} · ${t?short(t.name):'Keine Reise'}${p?' · '+p.name:''}`;}
function render(){setSubtitle();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));const v=$('#view');if(state.route==='home')v.innerHTML=viewHome();if(state.route==='track')v.innerHTML=viewTrack();if(state.route==='history')v.innerHTML=viewHistory();if(state.route==='stats')v.innerHTML=viewStats();if(state.route==='trips')v.innerHTML=viewTrips();if(state.route==='data')v.innerHTML=viewData();if(state.route==='settings')v.innerHTML=viewSettings();bindView();}
function pkgName(id){return (state.packages.find(p=>p.id===id)||{}).name||id||'Kein Paket'}
function pkgStatus(d,pid){if(!pid||pid==='none')return 'not_included';return (d.packages&&d.packages[pid])||'unclear'}
function statusBadge(s){return s==='included'?'<span class="badge ok">enthalten</span>':s==='not_included'?'<span class="badge bad">nicht enthalten</span>':'<span class="badge warn">unklar</span>'}
function cats(){const fromData=[...new Set(state.drinks.map(d=>d.category).filter(Boolean))];return preferredCategories.filter(c=>c==='Empfohlen'||c==='Favoriten'||c==='Alle'||fromData.includes(c)).concat(fromData.filter(c=>!preferredCategories.includes(c)));}
function isQuick(d){const hay=`${d.name} ${d.category}`.toLowerCase();return quickTerms.some(t=>hay.includes(t));}
function score(d){let s=0;if(state.favorites.includes(d.id))s-=10000;if(isQuick(d))s-=5000;const c=preferredCategories.indexOf(d.category);s+=c>=0?c*100:2500;const n=d.name.toLowerCase();const hit=quickTerms.findIndex(t=>n.includes(t));if(hit>=0)s+=hit;return s;}
function filteredDrinks(){let list=state.drinks.slice();if(state.cat==='Favoriten')list=list.filter(d=>state.favorites.includes(d.id));else if(state.cat==='Empfohlen')list=list.filter(d=>state.favorites.includes(d.id)||isQuick(d));else if(state.cat!=='Alle')list=list.filter(d=>d.category===state.cat);if(state.query){const q=state.query.toLowerCase();list=list.filter(d=>`${d.name} ${d.category} ${d.notes||''}`.toLowerCase().includes(q));}return list.sort((a,b)=>score(a)-score(b)||a.name.localeCompare(b.name,'de'));}
function viewHome(){const logs=currentLogs();const today=new Date().toDateString();const todayLogs=logs.filter(l=>new Date(l.ts).toDateString()===today);const included=logs.filter(l=>l.status==='included').reduce((s,l)=>s+(+l.price||0),0);const costs=currentPersons().reduce((s,p)=>s+(+p.packagePrice||0),0);const t=currentTrip();return `<section class="grid"><div class="card hero"><h2>${esc(t?t.name:'Reise fehlt')}</h2><p class="muted">${esc([t?.ship,dateRange(t)].filter(Boolean).join(' · '))}</p></div><div class="kpi"><div><b>${todayLogs.length}</b><span class="muted">Heute</span></div><div><b>${logs.length}</b><span class="muted">Reise</span></div><div><b>${eur(included-costs)}</b><span class="muted">Ersparnis</span></div></div><div class="smallgrid"><button class="primary" data-action="goTrack">Getränk erfassen</button><button class="secondary" data-action="goStats">Auswertung</button></div><div class="smallgrid"><button class="secondary" data-action="goSettings">Personen / Gerät</button><button class="secondary" data-action="goTrips">Reisen</button></div><div class="card"><h3>Schnellzugriff</h3>${quickHomeDrinks().map(d=>`<button class="quickdrink" data-log="${d.id}"><span>${esc(icon(d.category))} ${esc(d.name)}</span><b>${eur(d.price)}</b></button>`).join('')||'<p class="muted">Favoriten oder Verlauf erzeugen hier Schnellzugriffe.</p>'}</div><div class="card"><h3>Zuletzt erfasst</h3>${logs.slice(0,6).map(l=>logLine(l)).join('')||'<p class="muted">Noch keine Einträge.</p>'}</div><div class="card"><h3>Gerät</h3><div class="notice">${esc(state.settings.deviceName)}<br><span class="deviceid">${esc(state.settings.deviceId)}</span></div></div></section>`;}

function quickHomeDrinks(){const ids=[];for(const id of state.favorites)ids.push(id);for(const l of currentLogs().slice(0,20))ids.push(l.drinkId);for(const d of state.drinks.filter(isQuick).slice(0,12))ids.push(d.id);const seen=new Set();return ids.map(id=>state.drinks.find(d=>d.id===id)).filter(Boolean).filter(d=>!seen.has(d.id)&&seen.add(d.id)).slice(0,8);}
function viewTrack(){const persons=currentPersons();if(!currentTrip())return `<section class="grid"><div class="card"><h2>Reise erforderlich</h2><button class="primary" data-action="goTrips">Reise anlegen</button></div></section>`;if(!persons.length)return `<section class="grid"><div class="card"><h2>Person erforderlich</h2><p>Lege für diese Reise zuerst Personen und Pakete an.</p><button class="primary" data-action="goSettings">Setup starten</button></div></section>`;const person=persons.find(p=>p.id===state.selectedPerson)||persons[0];const drinks=filteredDrinks();return `<section class="grid"><div class="chips">${persons.map(p=>`<button class="chip ${p.id===person.id?'active':''}" data-person="${p.id}">${esc(p.name)}</button>`).join('')}</div><div class="card stack"><div class="quickrow"><input id="search" placeholder="Getränk suchen" value="${esc(state.query)}"><span class="count">${drinks.length}</span></div><div class="chips">${cats().map(c=>`<button class="chip ${c===state.cat?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div class="grid">${drinks.map(d=>drinkRow(d,person)).join('')||'<div class="card empty">Keine Treffer.</div>'}</div></section>`;}
function drinkRow(d,person){const fav=state.favorites.includes(d.id);const s=pkgStatus(d,person.packageId);return `<div class="card drink"><button class="favbtn ${fav?'active':''}" data-fav="${d.id}" aria-label="Favorit">${fav?'★':'☆'}</button><button class="drink-main" data-log="${d.id}"><span class="drink-title">${esc(icon(d.category))} ${esc(d.name)}</span><span class="muted">${esc(d.category||'')} · ${statusBadge(s)}</span></button><button class="mini" data-log="${d.id}">${eur(d.price)}</button></div>`}
function viewHistory(){const logs=currentLogs();return `<section class="grid"><div class="card"><h2>Verlauf bearbeiten</h2><p class="muted">Eintrag antippen, wenn falsch getrackt wurde. Importierte Einträge zeigen auch das erfassende Gerät.</p>${logs.slice(0,120).map(l=>logLine(l,true)).join('')||'<div class="empty">Noch keine Einträge.</div>'}</div></section>`;}
function logLine(l,actions=false){return `<div class="stat"><span><b>${esc(iconByStatus(l.status))} ${esc(l.drinkName)}</b><br><span class="muted">${new Date(l.ts).toLocaleString('de-DE')} · für ${esc(l.personName)} · erfasst auf ${esc(l.trackedByDeviceName||'unbekannt')} · ${statusBadge(l.status)}</span></span>${actions?`<span class="actions"><button class="mini" data-edit-log="${l.id}">Ändern</button><button class="mini bad" data-delete-log="${l.id}">Löschen</button></span>`:`<span>${eur(l.price)}</span>`}</div>`;}
function viewStats(){const persons=currentPersons();const logs=currentLogs();const rows=persons.map(p=>{const pl=logs.filter(l=>l.personId===p.id);const total=pl.reduce((s,l)=>s+(+l.price||0),0);const included=pl.filter(l=>l.status==='included').reduce((s,l)=>s+(+l.price||0),0);const unclear=pl.filter(l=>l.status==='unclear').reduce((s,l)=>s+(+l.price||0),0);const cost=+p.packagePrice||0;return {p,logs:pl,total,included,unclear,cost,saving:included-cost};});return `<section class="grid"><div class="card"><h2>Auswertung pro Reise</h2><div class="notice">Reise: <b>${esc(currentTrip()?.name||'')}</b></div>${rows.map(r=>`<div class="stat"><span><b>${esc(r.p.name)}</b><br><span class="muted">${pkgName(r.p.packageId)} · ${r.logs.length} Getränke</span></span><span>${eur(r.total)}</span></div><div class="stat"><span>Davon im Paket bewertet</span><span>${eur(r.included)}</span></div><div class="stat"><span>Unklar / prüfbar</span><span>${eur(r.unclear)}</span></div><div class="stat"><span>Paketpreis</span><span>${eur(r.cost)}</span></div><div class="stat"><span>Konservative Ersparnis</span><span>${eur(r.saving)}</span></div>`).join('')||'<p>Keine Personen angelegt.</p>'}</div><div class="card"><h3>Erfasst nach Gerät</h3>${byDevice(logs).map(x=>`<div class="stat"><span>${esc(x.name)}<br><span class="deviceid">${esc(x.id)}</span></span><span>${x.count}×</span></div>`).join('')||'<p class="muted">Noch keine Einträge.</p>'}</div><div class="card"><h3>Häufigste Getränke</h3>${topDrinks(logs).map(x=>`<div class="stat"><span>${esc(x.name)}</span><span>${x.count}×</span></div>`).join('')||'<p class="muted">Noch keine Einträge.</p>'}</div></section>`;}
function byDevice(logs){const m=new Map();for(const l of logs){const id=l.trackedByDeviceId||'unknown';const cur=m.get(id)||{id,name:l.trackedByDeviceName||'unbekannt',count:0};cur.count++;m.set(id,cur);}return [...m.values()].sort((a,b)=>b.count-a.count);}
function topDrinks(logs){const m=new Map();for(const l of logs)m.set(l.drinkName,(m.get(l.drinkName)||0)+1);return [...m.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count).slice(0,10)}
function viewTrips(){return `<section class="grid"><div class="card stack"><h2>Reise anlegen</h2><div class="field"><label>Name</label><input id="tName" placeholder="z. B. AIDA Norwegen 2026"></div><div class="field"><label>Schiff / Hinweis</label><input id="tShip" placeholder="z. B. AIDAnova"></div><div class="smallgrid"><div class="field"><label>Start</label><input id="tStart" type="date"></div><div class="field"><label>Ende</label><input id="tEnd" type="date"></div></div><button class="primary" data-action="addTrip">Reise speichern</button></div><div class="card"><h2>Reisen</h2>${state.trips.map(t=>`<div class="stat"><span><b>${esc(t.name)}</b><br><span class="muted">${esc([t.ship,dateRange(t)].filter(Boolean).join(' · '))} · ${currentLogsForTrip(t.id).length} Einträge</span></span><span class="actions"><button class="mini" data-select-trip="${t.id}">${t.id===state.selectedTrip?'Aktiv':'Wählen'}</button><button class="mini bad" data-delete-trip="${t.id}">Löschen</button></span></div>`).join('')}</div></section>`;}
function currentLogsForTrip(id){return state.logs.filter(l=>l.tripId===id)}
function viewSettings(){const persons=currentPersons();return `<section class="grid"><div class="card stack"><h2>Gerät</h2><div class="field"><label>Gerätename / wer trackt?</label><input id="deviceName" value="${esc(state.settings.deviceName||'')}"></div><div class="notice">Eindeutige Geräte-ID:<br><span class="deviceid">${esc(state.settings.deviceId||'')}</span><br>Diese ID wird in jedem Eintrag gespeichert und verhindert Dubletten beim Zusammenführen.</div><button class="primary" data-action="saveDevice">Gerät speichern</button></div><div class="card stack"><h2>Person für aktuelle Reise</h2><div class="field"><label>Name</label><input id="pName" placeholder="z. B. Fabian"></div><div class="field"><label>Getränkepaket</label><select id="pPkg">${state.packages.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Paketpreis gesamt</label><input id="pPrice" type="number" step="0.01" placeholder="0,00"></div><button class="primary" data-action="addPerson">Person speichern</button></div><div class="card"><h2>Personen dieser Reise</h2>${persons.map(p=>`<div class="stat"><span><b>${esc(p.name)}</b><br><span class="muted">${pkgName(p.packageId)} · ${eur(p.packagePrice)}</span></span><button class="mini bad" data-delete-person="${p.id}">Löschen</button></div>`).join('')||'<p>Noch keine Personen.</p>'}</div></section>`;}
function viewData(){const b=state.settings.barkarteVersion||{};return `<section class="grid"><div class="card stack"><h2>Info</h2><div class="notice"><b>App:</b> Version ${APP_VERSION}<br><b>Barkarte:</b> AIDA 01.11.2025<br><b>Getränke:</b> ${state.drinks.length}<br><b>Aktuelle Reise:</b> ${esc(currentTrip()?.name||'')}<br><b>Gerät:</b> ${esc(state.settings.deviceName)}<br><span class="deviceid">${esc(state.settings.deviceId)}</span></div><button class="primary" data-action="export">Backup / Gerätedaten exportieren</button><button class="secondary" data-action="importBackup">Backup importieren und zusammenführen</button><button class="secondary" data-action="importBarkarte">Barkarte importieren (JSON/CSV/Text)</button><div class="notice">Beim Import werden Einträge anhand ihrer eindeutigen Eintrags-ID zusammengeführt. Jeder neue Eintrag enthält die Geräte-ID. Bereits vorhandene Einträge werden nicht doppelt übernommen.</div></div><div class="card changelog"><h2>Changelog</h2>${CHANGELOG.map(c=>`<h3>${c.v}</h3><ul>${c.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`).join('')}</div></section>`;}
function bindView(){
 $$('[data-person]').forEach(b=>b.onclick=()=>{state.selectedPerson=b.dataset.person;render();});$$('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render();});const s=$('#search');if(s)s.oninput=e=>{state.query=e.target.value;render();};$$('[data-log]').forEach(b=>b.onclick=()=>addLog(b.dataset.log));$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));$$('[data-edit-log]').forEach(b=>b.onclick=()=>openEditLog(b.dataset.editLog));$$('[data-delete-log]').forEach(b=>b.onclick=()=>deleteLog(b.dataset.deleteLog));$$('[data-delete-person]').forEach(b=>b.onclick=()=>deletePerson(b.dataset.deletePerson));$$('[data-select-trip]').forEach(b=>b.onclick=()=>selectTrip(b.dataset.selectTrip));$$('[data-delete-trip]').forEach(b=>b.onclick=()=>deleteTrip(b.dataset.deleteTrip));$$('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]&&actions[b.dataset.action]());
}
async function toggleFav(id){const set=new Set(state.favorites);set.has(id)?set.delete(id):set.add(id);state.favorites=[...set];await putSetting('favorites',state.favorites);render();}
async function addLog(drinkId){const p=currentPersons().find(x=>x.id===state.selectedPerson),d=state.drinks.find(x=>x.id===drinkId),t=currentTrip();if(!p||!d||!t)return;const id=`${state.settings.deviceId}_${uid()}`;await put('logs',{id,ts:Date.now(),tripId:t.id,tripKey:t.tripKey,personId:p.id,personName:p.name,drinkId:d.id,drinkName:d.name,price:+d.price||0,status:pkgStatus(d,p.packageId),trackedByDeviceId:state.settings.deviceId,trackedByDeviceName:state.settings.deviceName});await load();render();}
async function deleteLog(id){if(confirm('Eintrag wirklich löschen?')){await del('logs',id);await load();render();}}
function openEditLog(id){const l=state.logs.find(x=>x.id===id);if(!l)return;$('#editId').value=l.id;$('#editTrip').innerHTML=state.trips.map(t=>`<option value="${t.id}" ${t.id===l.tripId?'selected':''}>${esc(t.name)}</option>`).join('');$('#editPerson').innerHTML=state.persons.filter(p=>p.tripId===l.tripId).map(p=>`<option value="${p.id}" ${p.id===l.personId?'selected':''}>${esc(p.name)}</option>`).join('');$('#editDrink').innerHTML=state.drinks.slice().sort((a,b)=>score(a)-score(b)||a.name.localeCompare(b.name,'de')).map(d=>`<option value="${d.id}" ${d.id===l.drinkId?'selected':''}>${esc(d.name)} · ${eur(d.price)}</option>`).join('');$('#editPrice').value=Number(l.price||0).toFixed(2);$('#editStatus').value=l.status||'unclear';$('#editTs').value=toLocalInput(l.ts);$('#editTrip').onchange=()=>{$('#editPerson').innerHTML=state.persons.filter(p=>p.tripId===$('#editTrip').value).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')};$('#editDialog').showModal();}
async function saveEditLog(){const id=$('#editId').value;const old=state.logs.find(x=>x.id===id);if(!old)return;const t=state.trips.find(x=>x.id===$('#editTrip').value);const p=state.persons.find(x=>x.id===$('#editPerson').value);const d=state.drinks.find(x=>x.id===$('#editDrink').value);if(!t||!p||!d)return;const ts=new Date($('#editTs').value).getTime()||Date.now();const log={...old,ts,tripId:t.id,tripKey:t.tripKey,personId:p.id,personName:p.name,drinkId:d.id,drinkName:d.name,price:Number($('#editPrice').value)||0,status:$('#editStatus').value,editedAt:new Date().toISOString()};await put('logs',log);await load();state.route='history';render();}
async function deletePerson(id){if(confirm('Person und zugehörige Einträge dieser Person löschen?')){await del('persons',id);for(const l of state.logs.filter(x=>x.personId===id))await del('logs',l.id);await load();render();}}
async function selectTrip(id){state.selectedTrip=id;await putSetting('currentTripId',id);await load();state.route='home';render();}
async function deleteTrip(id){if(state.trips.length<=1)return alert('Mindestens eine Reise muss bestehen bleiben.');if(confirm('Reise einschließlich Personen und Einträgen löschen?')){for(const p of state.persons.filter(x=>x.tripId===id))await del('persons',p.id);for(const l of state.logs.filter(x=>x.tripId===id))await del('logs',l.id);await del('trips',id);await load();await selectTrip(state.trips[0].id);}}
const actions={goTrack(){state.route='track';render();},goStats(){state.route='stats';render();},goTrips(){state.route='trips';render();},goSettings(){state.route='settings';render();},goData(){state.route='data';render();},async saveDevice(){const n=$('#deviceName').value.trim()||'Dieses Gerät';await putSetting('deviceName',n);await load();render();},async addTrip(){const name=$('#tName').value.trim();if(!name)return alert('Reisename fehlt.');const t={id:'trip_'+uid(),name,ship:$('#tShip').value.trim(),startDate:$('#tStart').value,endDate:$('#tEnd').value,tripKey:tripKey({name,startDate:$('#tStart').value,endDate:$('#tEnd').value}),createdAt:new Date().toISOString()};await put('trips',t);await putSetting('currentTripId',t.id);state.selectedTrip=t.id;await load();state.route='settings';render();},async addPerson(){const name=$('#pName').value.trim();if(!name)return alert('Name fehlt.');await put('persons',{id:'person_'+uid(),tripId:state.selectedTrip,name,packageId:$('#pPkg').value,packagePrice:Number($('#pPrice').value)||0});await load();state.route='track';render();},export(){const data={appVersion:APP_VERSION,exportedAt:new Date().toISOString(),device:{id:state.settings.deviceId,name:state.settings.deviceName},currentTripId:state.selectedTrip,trips:state.trips,persons:state.persons,drinks:state.drinks,logs:state.logs,favorites:state.favorites};download(JSON.stringify(data,null,2),`getraenketracker-${safeName(state.settings.deviceName)}-${new Date().toISOString().slice(0,10)}.json`,'application/json');},importBackup(){pick('.json',async text=>{const data=JSON.parse(text);const r=await mergeBackup(data);await load();alert(`Import abgeschlossen.\nNeue Reisen: ${r.trips}\nNeue Personen: ${r.persons}\nNeue Einträge: ${r.logs}\nÜbersprungene Dubletten: ${r.duplicates}`);render();});},importBarkarte(){pick('.json,.csv,.txt',async text=>{let drinks=[];if(text.trim().startsWith('{')||text.trim().startsWith('[')){const data=JSON.parse(text);drinks=Array.isArray(data)?data:(data.drinks||[]);}else{drinks=parseCsvDrinks(text);}if(!drinks.length)return alert('Keine Getränke erkannt.');let changed=0;for(const d of drinks){d.id=d.id||slug(d.name);d.packages=d.packages||{};await put('drinks',d);changed++;}await load();alert(`${changed} Getränke importiert/aktualisiert.`);render();});}};
async function mergeBackup(data){let res={trips:0,persons:0,logs:0,duplicates:0};const tripMap=new Map();for(const it of data.trips||[]){const key=it.tripKey||tripKey(it);let local=state.trips.find(t=>(t.tripKey||tripKey(t))===key);if(!local){local={...it,id:it.id||'trip_'+uid(),tripKey:key};await put('trips',local);state.trips.push(local);res.trips++;}tripMap.set(it.id,local.id);}const personMap=new Map();const allPersons=await all('persons');for(const ip of data.persons||[]){const mappedTrip=tripMap.get(ip.tripId)||ip.tripId||state.selectedTrip;let local=allPersons.find(p=>p.tripId===mappedTrip&&norm(p.name)===norm(ip.name));if(!local){local={...ip,id:ip.id||'person_'+uid(),tripId:mappedTrip};await put('persons',local);allPersons.push(local);res.persons++;}personMap.set(ip.id,local.id);}const existing=new Set((await all('logs')).map(l=>l.id));for(const il of data.logs||[]){if(existing.has(il.id)){res.duplicates++;continue;}const mappedTrip=tripMap.get(il.tripId)||il.tripId||state.selectedTrip;const mappedPerson=personMap.get(il.personId)||il.personId;await put('logs',{...il,tripId:mappedTrip,personId:mappedPerson,trackedByDeviceId:il.trackedByDeviceId||data.device?.id||'unknown',trackedByDeviceName:il.trackedByDeviceName||data.device?.name||'unbekannt'});res.logs++;}if(data.favorites){const set=new Set([...state.favorites,...data.favorites]);await putSetting('favorites',[...set]);}return res;}
function pick(accept,cb){const i=$('#fileInput');i.accept=accept;i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsText(f);i.value='';};i.click();}
function parseCsvDrinks(text){const lines=text.split(/\r?\n/).filter(Boolean);const head=lines.shift().split(';').map(x=>x.trim().toLowerCase());return lines.map(line=>{const c=line.split(';');const obj={};head.forEach((h,i)=>obj[h]=c[i]);return {id:slug(obj.id||obj.name),name:obj.name||obj.getränk||obj.getraenk,category:obj.category||obj.kategorie||'Import',price:Number(String(obj.price||obj.preis||'0').replace(',','.')),packages:{}};}).filter(d=>d.name);}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function toLocalInput(ts){const d=new Date(ts);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
function short(s){return String(s||'').length>18?String(s).slice(0,18)+'…':String(s||'')}
function dateRange(t){return [t?.startDate,t?.endDate].filter(Boolean).join('–')}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function tripKey(t){return [norm(t.name),t.startDate||'',t.endDate||''].join('|')}
function safeName(s){return norm(s).replace(/_/g,'-')||'geraet'}
function slug(s){return norm(s||'getraenk')+'_'+uid().slice(0,4)}
function icon(cat){cat=String(cat||'').toLowerCase();if(cat.includes('kaffee')||cat.includes('heiß'))return '☕';if(cat.includes('soft')||cat.includes('wasser')||cat.includes('saft'))return '🥤';if(cat.includes('bier'))return '🍺';if(cat.includes('wein'))return '🍷';if(cat.includes('sprizz')||cat.includes('cocktail')||cat.includes('longdrink'))return '🍹';if(cat.includes('spirit'))return '🥃';return '•'}
function iconByStatus(s){return s==='included'?'🟢':s==='not_included'?'🔴':'🟡'}
bootstrap().catch(e=>{console.error(e);$('#view').innerHTML='<div class="card"><h2>Fehler beim Start</h2><p>'+esc(e.message)+'</p></div>';});
