'use strict';
const DB_NAME='gt_db_v2';
const DB_VERSION=2;
const APP_VERSION='2.3.0';
const DATA_VERSION='2025-11-01_aida_barkarte_v2_3';
let db;
let state={route:'track',persons:[],drinks:[],packages:[],logs:[],favorites:[],selectedPerson:null,query:'',cat:'Empfohlen'};
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const eur=n=>(Number(n)||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const routeNames={track:'Tracken',history:'Verlauf',stats:'Auswertung',data:'Daten',settings:'Setup'};
const preferredCategories=['Empfohlen','Favoriten','Heißgetränke','Softdrinks','Wasser','Säfte, Nektare & Schorlen','Juicy Cocktails','Kids & Teens Cocktails','Milchshakes','Biere','Longdrinks','Sprizz','Cocktails','Weine','Prickelndes','Spirituosen','Alle'];
const quickTerms=['kaffee','cappuccino','latte','espresso','kakao','tee','coca-cola','cola','fanta','sprite','wasser','mineralwasser','sodawasser','apfelsaft','orangensaft','aida iced tea','aida lemonade','dodo','erdbeer-milchshake','radeberger pilsner','aperol sprizz','hugo'];
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;['settings','persons','drinks','logs'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'});});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
async function getSetting(id){return new Promise((res,rej)=>{const r=tx('settings').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function putSetting(obj){return put('settings',obj)}
async function load(){state.persons=await all('persons');state.drinks=await all('drinks');state.logs=(await all('logs')).sort((a,b)=>b.ts-a.ts);state.favorites=((await getSetting('favorites'))||{value:[]}).value||[];if(!state.selectedPerson&&state.persons[0])state.selectedPerson=state.persons[0].id;}
async function bootstrap(){db=await openDb();state.packages=await fetch('data/pakete.json').then(r=>r.json()).catch(()=>[]);const data=await fetch('data/barkarte.json').then(r=>r.json());const current=await getSetting('barkarteVersion');const has=(await all('drinks')).length;if(!has||!current||current.value!==DATA_VERSION){for(const d of data.drinks) await put('drinks',d);await putSetting({id:'barkarteVersion',value:DATA_VERSION,source:data.source||'AIDA Barkarte',updatedAt:new Date().toISOString(),count:data.drinks.length});}
await putSetting({id:'appVersion',value:APP_VERSION,updatedAt:new Date().toISOString()});await load();bindStatic();render();if('serviceWorker'in navigator) navigator.serviceWorker.register('sw.js');}
function bindStatic(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-route]');if(nav){state.route=nav.dataset.route;render();}});$('#menuBtn').onclick=()=>$('#menuDialog').showModal();$('#menuDialog').addEventListener('close',()=>{const v=$('#menuDialog').returnValue;if(v&&v!=='close'){state.route=v;render();}});$('#editDialog').addEventListener('close',()=>{if($('#editDialog').returnValue==='save')saveEditLog();});}
function setSubtitle(){const p=state.persons.find(x=>x.id===state.selectedPerson);$('#subtitle').textContent=`Version ${APP_VERSION} · ${p?p.name+' · ':''}AIDA 01.11.2025`;}
function render(){setSubtitle();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));const v=$('#view');if(state.route==='track')v.innerHTML=viewTrack();if(state.route==='history')v.innerHTML=viewHistory();if(state.route==='stats')v.innerHTML=viewStats();if(state.route==='data')v.innerHTML=viewData();if(state.route==='settings')v.innerHTML=viewSettings();bindView();}
function pkgName(id){return (state.packages.find(p=>p.id===id)||{}).name||id||'Kein Paket'}
function pkgStatus(d,pid){if(!pid||pid==='none')return 'not_included';return (d.packages&&d.packages[pid])||'unclear'}
function statusBadge(s){return s==='included'?'<span class="badge ok">enthalten</span>':s==='not_included'?'<span class="badge bad">nicht enthalten</span>':'<span class="badge warn">unklar</span>'}
function cats(){const fromData=[...new Set(state.drinks.map(d=>d.category).filter(Boolean))];return preferredCategories.filter(c=>c==='Empfohlen'||c==='Favoriten'||c==='Alle'||fromData.includes(c)).concat(fromData.filter(c=>!preferredCategories.includes(c)));}
function isQuick(d){const hay=`${d.name} ${d.category}`.toLowerCase();return quickTerms.some(t=>hay.includes(t));}
function score(d){let s=0;if(state.favorites.includes(d.id))s-=10000;if(isQuick(d))s-=5000;const c=preferredCategories.indexOf(d.category);if(c>=0)s+=c*100;else s+=2500;const n=d.name.toLowerCase();const hit=quickTerms.findIndex(t=>n.includes(t));if(hit>=0)s+=hit;return s;}
function filteredDrinks(){let list=state.drinks.slice();if(state.cat==='Favoriten')list=list.filter(d=>state.favorites.includes(d.id));else if(state.cat==='Empfohlen')list=list.filter(d=>state.favorites.includes(d.id)||isQuick(d));else if(state.cat!=='Alle')list=list.filter(d=>d.category===state.cat);if(state.query){const q=state.query.toLowerCase();list=list.filter(d=>`${d.name} ${d.category} ${d.notes||''}`.toLowerCase().includes(q));}return list.sort((a,b)=>score(a)-score(b)||a.name.localeCompare(b.name,'de'));}
function viewTrack(){if(!state.persons.length)return `<section class="grid"><div class="card"><h2>Ersteinrichtung erforderlich</h2><p>Lege zuerst Personen und Pakete an.</p><button class="primary" data-action="setup">Setup starten</button></div></section>`;const person=state.persons.find(p=>p.id===state.selectedPerson)||state.persons[0];const drinks=filteredDrinks();return `<section class="grid"><div class="chips">${state.persons.map(p=>`<button class="chip ${p.id===person.id?'active':''}" data-person="${p.id}">${esc(p.name)}</button>`).join('')}</div><div class="card stack"><div class="quickrow"><input id="search" placeholder="Getränk suchen" value="${esc(state.query)}"><span class="count">${drinks.length}</span></div><div class="chips">${cats().map(c=>`<button class="chip ${c===state.cat?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div class="grid">${drinks.map(d=>drinkRow(d,person)).join('')||'<div class="card empty">Keine Treffer.</div>'}</div></section>`;}
function drinkRow(d,person){const fav=state.favorites.includes(d.id);const s=pkgStatus(d,person.packageId);return `<div class="card drink"><button class="favbtn ${fav?'active':''}" data-fav="${d.id}" aria-label="Favorit">${fav?'★':'☆'}</button><button class="drink-main" data-log="${d.id}"><span class="drink-title">${esc(d.name)}</span><span class="muted">${esc(d.category||'')} · ${statusBadge(s)}</span></button><button class="mini" data-log="${d.id}">${eur(d.price)}</button></div>`}
function viewHistory(){return `<section class="grid"><div class="card"><h2>Verlauf bearbeiten</h2><p class="muted">Falsch erfasste Getränke kannst du hier ändern oder löschen.</p>${state.logs.slice(0,80).map(l=>`<div class="stat"><span><b>${esc(l.drinkName)}</b><br><span class="muted">${new Date(l.ts).toLocaleString('de-DE')} · ${esc(l.personName)} · ${statusBadge(l.status)}</span></span><span class="actions"><button class="mini" data-edit-log="${l.id}">Ändern</button><button class="mini bad" data-delete-log="${l.id}">Löschen</button></span></div>`).join('')||'<div class="empty">Noch keine Einträge.</div>'}</div></section>`;}
function viewStats(){const rows=state.persons.map(p=>{const logs=state.logs.filter(l=>l.personId===p.id);const total=logs.reduce((s,l)=>s+(Number(l.price)||0),0);const included=logs.filter(l=>l.status==='included').reduce((s,l)=>s+(Number(l.price)||0),0);const unclear=logs.filter(l=>l.status==='unclear').reduce((s,l)=>s+(Number(l.price)||0),0);const cost=Number(p.packagePrice)||0;return {p,logs,total,included,unclear,cost,saving:included-cost};});return `<section class="grid"><div class="card"><h2>Auswertung</h2>${rows.map(r=>`<div class="stat"><span><b>${esc(r.p.name)}</b><br><span class="muted">${pkgName(r.p.packageId)} · ${r.logs.length} Getränke</span></span><span>${eur(r.total)}</span></div><div class="stat"><span>Davon im Paket bewertet</span><span>${eur(r.included)}</span></div><div class="stat"><span>Unklar / prüfbar</span><span>${eur(r.unclear)}</span></div><div class="stat"><span>Paketpreis</span><span>${eur(r.cost)}</span></div><div class="stat"><span>Konservative Ersparnis</span><span>${eur(r.saving)}</span></div>`).join('')||'<p>Keine Personen angelegt.</p>'}</div><div class="card"><h3>Häufigste Getränke</h3>${topDrinks().map(x=>`<div class="stat"><span>${esc(x.name)}</span><span>${x.count}×</span></div>`).join('')||'<p class="muted">Noch keine Einträge.</p>'}</div></section>`;}
function topDrinks(){const m=new Map();for(const l of state.logs)m.set(l.drinkName,(m.get(l.drinkName)||0)+1);return [...m.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count).slice(0,10)}
function viewSettings(){return `<section class="grid"><div class="card stack"><h2>Person anlegen</h2><div class="field"><label>Name</label><input id="pName" placeholder="z. B. Fabian"></div><div class="field"><label>Getränkepaket</label><select id="pPkg">${state.packages.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Paketpreis gesamt</label><input id="pPrice" type="number" step="0.01" placeholder="0,00"></div><button class="primary" data-action="addPerson">Person speichern</button></div><div class="card"><h2>Personen</h2>${state.persons.map(p=>`<div class="stat"><span><b>${esc(p.name)}</b><br><span class="muted">${pkgName(p.packageId)} · ${eur(p.packagePrice)}</span></span><button class="mini bad" data-delete-person="${p.id}">Löschen</button></div>`).join('')||'<p>Noch keine Personen.</p>'}</div></section>`;}
function viewData(){return `<section class="grid"><div class="card stack"><h2>Info</h2><div class="notice"><b>App:</b> Version ${APP_VERSION}<br><b>Barkarte:</b> AIDA 01.11.2025<br><b>Getränke:</b> ${state.drinks.length}<br><b>Favoriten:</b> ${state.favorites.length}</div><button class="primary" data-action="export">Backup exportieren</button><button class="secondary" data-action="importBackup">Backup importieren</button><button class="secondary" data-action="importBarkarte">Barkarte importieren (JSON/CSV/Text)</button><div class="notice">PDF-Auslesen bleibt bewusst getrennt. Paketstatus wird nur gesetzt, wenn eindeutig; sonst bleibt der Eintrag unklar.</div></div></section>`;}
function bindView(){$$('[data-person]').forEach(b=>b.onclick=()=>{state.selectedPerson=b.dataset.person;render();});$$('[data-cat]').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render();});const s=$('#search');if(s)s.oninput=e=>{state.query=e.target.value;render();};$$('[data-log]').forEach(b=>b.onclick=()=>addLog(b.dataset.log));$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.fav));$$('[data-edit-log]').forEach(b=>b.onclick=()=>openEditLog(b.dataset.editLog));$$('[data-delete-log]').forEach(b=>b.onclick=()=>deleteLog(b.dataset.deleteLog));$$('[data-delete-person]').forEach(b=>b.onclick=()=>deletePerson(b.dataset.deletePerson));$$('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]&&actions[b.dataset.action]());}
async function toggleFav(id){const set=new Set(state.favorites);set.has(id)?set.delete(id):set.add(id);state.favorites=[...set];await putSetting({id:'favorites',value:state.favorites,updatedAt:new Date().toISOString()});render();}
async function addLog(drinkId){const p=state.persons.find(x=>x.id===state.selectedPerson),d=state.drinks.find(x=>x.id===drinkId);if(!p||!d)return;await put('logs',{id:uid(),ts:Date.now(),personId:p.id,personName:p.name,drinkId:d.id,drinkName:d.name,price:Number(d.price)||0,status:pkgStatus(d,p.packageId)});await load();render();}
async function deleteLog(id){if(confirm('Eintrag wirklich löschen?')){await del('logs',id);await load();render();}}
function openEditLog(id){const l=state.logs.find(x=>x.id===id);if(!l)return;$('#editId').value=l.id;$('#editPerson').innerHTML=state.persons.map(p=>`<option value="${p.id}" ${p.id===l.personId?'selected':''}>${esc(p.name)}</option>`).join('');$('#editDrink').innerHTML=state.drinks.slice().sort((a,b)=>score(a)-score(b)||a.name.localeCompare(b.name,'de')).map(d=>`<option value="${d.id}" ${d.id===l.drinkId?'selected':''}>${esc(d.name)} · ${eur(d.price)}</option>`).join('');$('#editPrice').value=Number(l.price||0).toFixed(2);$('#editStatus').value=l.status||'unclear';$('#editTs').value=toLocalInput(l.ts);$('#editDialog').showModal();}
async function saveEditLog(){const id=$('#editId').value;const old=state.logs.find(x=>x.id===id);if(!old)return;const p=state.persons.find(x=>x.id===$('#editPerson').value);const d=state.drinks.find(x=>x.id===$('#editDrink').value);const ts=new Date($('#editTs').value).getTime()||Date.now();const log={...old,ts,personId:p.id,personName:p.name,drinkId:d.id,drinkName:d.name,price:Number($('#editPrice').value)||0,status:$('#editStatus').value};await put('logs',log);await load();state.route='history';render();}
async function deletePerson(id){if(confirm('Person und zugehörige Einträge löschen?')){await del('persons',id);for(const l of state.logs.filter(x=>x.personId===id))await del('logs',l.id);await load();render();}}
const actions={setup(){state.route='settings';render();},async addPerson(){const name=$('#pName').value.trim();if(!name)return alert('Name fehlt.');await put('persons',{id:uid(),name,packageId:$('#pPkg').value,packagePrice:Number($('#pPrice').value)||0});await load();state.route='track';render();},export(){const data={version:APP_VERSION,exportedAt:new Date().toISOString(),persons:state.persons,drinks:state.drinks,logs:state.logs,favorites:state.favorites};download(JSON.stringify(data,null,2),'getraenketracker-backup.json','application/json');},importBackup(){pick('.json',async text=>{const data=JSON.parse(text);for(const p of data.persons||[])await put('persons',p);for(const d of data.drinks||[])await put('drinks',d);for(const l of data.logs||[])await put('logs',l);if(data.favorites)await putSetting({id:'favorites',value:data.favorites});await load();render();});},importBarkarte(){pick('.json,.csv,.txt',async text=>{let drinks=[];if(text.trim().startsWith('{')||text.trim().startsWith('[')){const data=JSON.parse(text);drinks=Array.isArray(data)?data:(data.drinks||[]);}else{drinks=parseCsvDrinks(text);}if(!drinks.length)return alert('Keine Getränke erkannt.');let changed=0;for(const d of drinks){d.id=d.id||slug(d.name);d.packages=d.packages||{};await put('drinks',d);changed++;}await load();alert(`${changed} Getränke importiert/aktualisiert.`);render();});}};
function pick(accept,cb){const i=$('#fileInput');i.accept=accept;i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>cb(String(r.result));r.readAsText(f);i.value='';};i.click();}
function parseCsvDrinks(text){const lines=text.split(/\r?\n/).filter(Boolean);const head=lines.shift().split(';').map(x=>x.trim().toLowerCase());return lines.map(line=>{const c=line.split(';');const obj={};head.forEach((h,i)=>obj[h]=c[i]);return {id:slug(obj.id||obj.name),name:obj.name||obj.getränk||obj.getraenk,category:obj.category||obj.kategorie||'Import',price:Number(String(obj.price||obj.preis||'0').replace(',','.')),packages:{}};}).filter(d=>d.name);}
function slug(s){return String(s||'getraenk').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')+'_'+uid().slice(0,4)}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function toLocalInput(ts){const d=new Date(ts);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
bootstrap().catch(e=>{console.error(e);$('#view').innerHTML='<div class="card"><h2>Fehler beim Start</h2><p>'+esc(e.message)+'</p></div>';});
